export const CITIES = [
  'Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen',
  'Almere', 'Breda', 'Nijmegen', 'Enschede', 'Haarlem', 'Arnhem', 'Zaanstad', 'Maastricht',
  'Leiden', 'Delft', 'Zwolle',
  'Antwerp', 'Brussels', 'Ghent', 'Bruges',
  'London', 'Manchester', 'Birmingham', 'Edinburgh', 'Glasgow', 'Liverpool', 'Bristol', 'Leeds',
  'Dublin', 'Cork',
  'Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice',
  'Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Dusseldorf',
  'Madrid', 'Barcelona', 'Valencia', 'Seville',
  'Lisbon', 'Porto',
  'Rome', 'Milan', 'Naples', 'Turin',
  'Vienna', 'Zurich', 'Geneva', 'Copenhagen', 'Stockholm', 'Oslo', 'Helsinki', 'Warsaw',
  'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio',
  'San Diego', 'Dallas', 'Austin', 'San Jose', 'San Francisco', 'Seattle', 'Denver', 'Boston',
  'Miami', 'Atlanta', 'Portland', 'Nashville', 'Detroit', 'Minneapolis',
  'Toronto', 'Vancouver', 'Montreal', 'Ottawa', 'Calgary',
  'Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Auckland',
] as const
